apiVersion: v1
kind: Service
metadata:
  name: cube3d-backend-service
  namespace: cube
spec:
  selector:
    app: cube3d-backend
  ports:    
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
    - name: https     
      port: 443
      targetPort: 8080
      protocol: TCP
  type: ClusterIP