#spring:
#  security:
#    oauth2:
#      authorizationserver:
#        issuer: http://auth-server:8200
#        client:
#          cube-client:
#            registration:
#              client-id: cube-client
#              client-secret: "{noop}secret"
#              client-name: Cube Client
#              client-authentication-methods:
#                - client_secret_basic
#                - client_secret_post
#              authorization-grant-types:
#                - authorization_code
#                - refresh_token
#              redirect-uris:
#                - https://localhost:8080/spring/oidc/callback
#              scopes:
#                - openid