apiVersion: v1
kind: Service
metadata:
  name: security-server-service
  namespace: cube
spec:
  selector:
    app: security-server
  ports:    
    - name: http
      port: 80
      targetPort: 8443
      protocol: TCP
    - name: https     
      port: 443
      targetPort: 8443
      protocol: TCP
  type: ClusterIP